---
abstract: 'GNOME applet for OpenPGP text encryption'
author:
  - 'Tails developers <tails@boum.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: gpl,artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenPGP_Applet
no_index:
  directory:
    - inc
    - share
requires:
  Any::Moose: 0
  Carp: 0
  DateTime: 0
  Encode: 0
  File::ShareDir: 0
  Glib: 0
  Gtk2: 0
  Gtk2::Gdk::Keysyms: 0
  Gtk2::SimpleList: 0
  I18N::Langinfo: 0
  IO::Handle: 0
  List::MoreUtils: 0
  Locale::gettext: 0
  POSIX: 0
  Switch: 0
  namespace::autoclean: 0
  perl: 5.10.0
version: 0.8
